home/urls.py
from django.urls import path
from .views import HomeViews, LogInViews, SignUpViews, LogOutViews

app_name = 'home_app'


urlpatterns = [
    path('',HomeViews.as_view(),name = 'home',),
    path('login/',LogInViews.as_view(),name = 'login',),
    path('signup/',SignUpViews.as_view(),name = 'signup',),
    path('logout/',LogOutViews.as_view(),name = 'logout',),
]

reciclo/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from trashcan.views import TrashCanViewSet, LevelViewSet
from rest_framework import routers

router = routers.DefaultRouter()
router.register('trash-cans', TrashCanViewSet)
router.register('levels', LevelViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    #Trashcan
    path('cans/', include('trashcan.urls', namespace='trashcan_app')),
    #Home
    path('', include('home.urls', namespace='home_app')),

    path('api-auth/', include('rest_framework.urls', namespace='rest_app')),
    path('api/', include(router.urls)),



]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

trashcan/urls.py
from django.urls import path
from . import views
from .views import CreateView, ListView

app_name = 'main_app'


urlpatterns = [
    path('', views.my_view,name = 'can-list',),
    path('crear/', CreateView.as_view(),name = 'can-create',),
    path('<int:pk>/', ListView.as_view(),name = 'can-detail',),
    #path('<int:id>/', views.my_view_detail,name = 'can-detail',),
]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm

class UserForm(ModelForm):
    

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if not first_name:
            raise forms.ValidationError(
                'El nombre es requerido.'
            )
        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')
        if not last_name:
            raise forms.ValidationError(
                'El nombre es requerido.'
            )
        return last_name


    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'password',
        )

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect

from .forms import UserForm


# Create your views here.



class HomeViews(TemplateView):
    template_name = "home/landing.html"

class LogInViews(View):
    template_name = "home/login.html"

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('home_app:home')
        context = {}
        return render(request, self.template_name, context)

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request,user)
            return redirect('home_app:home')
        return self.get(request)


class SignUpViews(View):
    template_name = "home/signup.html"


    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home_app:home')
        context = {
            'errors': kwargs.get('errors'),
        }
        return render(request, self.template_name, context)

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        
        form = UserForm(request.POST)
        
        if form.is_valid():
            
            username = request.POST['username']
            first_name = request.POST['first_name']
            last_name = request.POST['last_name']
            password = request.POST['password']
        


            
            user = User.objects.create(
                username=username,
                first_name=first_name,
                last_name=last_name,
                #password=password,
            )

            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request,user)
                return redirect('home_app:home')
        return self.get(request, errors=form.errors)

class LogOutViews(View):

    def get(self, request):
        logout(request)
        return redirect('home_app:home')

templates/home/landing.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Inicio</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>
<body>
    <style>
        a:hover{
            text-decoration: none;
        }

    
                .tachos, .sesion{
                    display: flex;
                    align-items: center;
                    justify-content: center
                }
        
                .spacing{
                    margin-right: 10px;
                }

    </style>
    <div class="container">
        <div class="col-md-12 ">
            <h1 class="text-center mt-5 mb-5">Bienvenido
                
                {% if user.is_authenticated %}
                    {{user.first_name}}
                {% endif %}
                    

            </h1>
            <p class="text-center">Con esta aplicación puedes saber como esta los tachos inteligentes</p>
        </div>
        {% if user.is_authenticated %}
            <div class="col-md-12">
                <div class="tachos">
                    <a href="{% url 'trashcan_app:can-list' %}" class="spacing">
                        <button type="button" class="btn  btn-info">Ver Tachos</button>
                    </a>
                    <a href="{% url 'home_app:logout' %}">
                        <button type="button" class="btn btn-outline-danger">Cerrar Sesión</button>
                    </a>
                </div>  
            </div>
        {% else %}
            <div class="col-md-12">
                <div class="sesion">
                    <a href="{% url 'home_app:login' %}" class="spacing">
                        <button type="button" class="btn btn-primary">Iniciar Sesión</button>
                    </a>
                    <a href="{% url 'home_app:signup' %}">
                        <button type="button" class="btn btn-success">Registro</button>
                    </a>
                </div>
            </div>            
        {% endif %}
            




    </div>
</body>
</html>

templates/home/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Inicio</title>
    
</head>
<body>
    <style>
        a:hover{
            text-decoration: none;
        }


       
                .tachos, .sesion{
                    display: flex;
                    align-items: center;
                    justify-content: center
                }
        
                .spacing{
                    margin-right: 10px;
                }

    </style>
    <div class="container">
        <div class="col-md-12 ">

            <div class="mt-5 mb-5">
                <a href="{% url 'home_app:home' %}">
                    <button type="button" class="btn btn-outline-secondary">Volver</button>
                </a>
            </div>


            <h1 class="text-center mt-5 mb-5">Iniciar Sesión</h1>
            <p class="text-center">Con esta aplicación puedes saber como esta los tachos inteligentes</p>
        </div>
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <form action="{% url 'home_app:login' %}" method="POST">
                        {% csrf_token %} 
                        <div class="form-group">
                            <label for="exampleInputEmail1">Email address</label>
                            <input type="text" class="form-control" name="username" placeholder="Ingresa Usuario">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Password</label>
                            <input type="password" class="form-control" name="password" placeholder="Ingresa Contraseña">
                        </div>
                        <button type="submit" class="btn btn-primary">Ingresar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/home/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Inicio</title>
    
</head>
<body>
    <style>
        a:hover{
            text-decoration: none;
        }
      
        .tachos, .sesion{
            display: flex;
            align-items: center;
            justify-content: center
        }

        .spacing{
            margin-right: 10px;
        }
    </style>
    <div class="container">
        <div class="col-md-12 ">

            <div class="mt-5 mb-5">
                <a href="{% url 'home_app:home' %}">
                    <button type="button" class="btn btn-outline-secondary">Volver</button>
                </a>
            </div>


            <h1 class="text-center mt-5 mb-5">Registrate</h1>
            <p class="text-center">Con esta aplicación puedes saber como esta los tachos inteligentes</p>
        </div>
        
        {% if errors %}
            {{errors}}
        {% endif %}
            
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <form action="{% url 'home_app:signup' %}" method="POST">
                        {% csrf_token %} 
                        <div class="form-group">
                            <label for="exampleInputEmail1">Usuario</label>
                            <input type="text" class="form-control" name="username" placeholder="Ingresa Usuario">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Password</label>
                            <input type="password" class="form-control" name="password" placeholder="Ingresa Contraseña">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Nombres</label>
                            <input type="text" class="form-control" name="first_name" placeholder="Ingresa tu nombre">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Apellidos</label>
                            <input type="text" class="form-control" name="last_name" placeholder="Ingresa tu apellido">
                        </div>
                        <button type="submit" class="btn btn-primary">Registrate</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>