home/urls.py
from django.urls import path
from .views import HomeViews, LogInViews, SignUpViews, LogOutViews

app_name = 'home_app'


urlpatterns = [
    path('',HomeViews.as_view(),name = 'home',),
    path('login/',LogInViews.as_view(),name = 'login',),
    path('signup/',SignUpViews.as_view(),name = 'signup',),
    path('logout/',LogOutViews.as_view(),name = 'logout',),
]

reciclo/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from trashcan.views import TrashCanViewSet, LevelViewSet
from rest_framework import routers

router = routers.DefaultRouter()
router.register('trash-cans', TrashCanViewSet)
router.register('levels', LevelViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    #Trashcan
    path('cans/', include('trashcan.urls', namespace='trashcan_app')),
    #Home
    path('', include('home.urls', namespace='home_app')),

    path('api-auth/', include('rest_framework.urls', namespace='rest_app')),
    path('api/', include(router.urls)),



]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

trashcan/urls.py
from django.urls import path
from . import views
from .views import CreateView, ListView

app_name = 'main_app'


urlpatterns = [
    path('', views.my_view,name = 'can-list',),
    path('crear/', CreateView.as_view(),name = 'can-create',),
    path('<int:pk>/', ListView.as_view(),name = 'can-detail',),
    #path('<int:id>/', views.my_view_detail,name = 'can-detail',),
]

trashcan/models.py
from django.contrib.auth.models import User
from django.db.models import Q
from django.db import models


# Create your models here.

class TrashCanQuerySet(models.QuerySet):

    def get_not_address(self):
        return self.filter(
            ~Q(address='') | ~Q(address__isnull = True),
        )



    def get_lat_lng(self):
        return self.filter(
            lat__isnull=False,
            lng__isnull=False

        )


    def get_barcode(self):
        return self.filter(
            ~Q(barcode=''),
            barcode__isnull = False
        )

    def get_gt_depth(self):
        return self.filter(
            depth__gt = 100
        )

    def count_barcode(self):
        return self.get_barcode().count()
    

    


class TrashCan(models.Model):

    depth = models.FloatField(help_text='Profundidad del tacho.')

    barcode = models.CharField(
        max_length=100,
        null = True,
        blank = True,
    )

    lat = models.FloatField(
        null=True,
        blank = True,
    )
    lng = models.FloatField(
        null=True,
        blank=True,
    )
    address = models.CharField(
        max_length = 300,
        blank = True,
    )

    recyclers = models.ManyToManyField(
        User,
        through='Harvest',
    )

    objects = TrashCanQuerySet.as_manager()

    def has_address(self):
        return bool(self.address)
        #if self.address:
        #    return True
        #return False

    @property
    def tiene_address(self):
        return self.has_address()

    #def set_address(self):
        #if self.tiene_address:
            #return
        #self.address='Almacen Principal'

    #def save(self,*args, **kwargs):
        #self.set_address()
        #super(TrashCan, self).save(*args, **kwargs)


    def __str__(self):
        return str(self.pk)

    class Meta:
        db_table = 'trash_can'



class LevelQuerySet(models.QuerySet):

    def get_levels(self, trash_can_pk):
        return self.filter(trash_can=trash_can_pk).order_by('-time')


class Level(models.Model):

    trash_can = models.ForeignKey(
        TrashCan, 
        related_name='levels',
        on_delete=models.CASCADE
    )

    time = models.DateTimeField(
        auto_now_add=True,
    )

    distance = models.FloatField(
        help_text = 'Distancia del cesor a la basura cm'
    )

    objects = LevelQuerySet.as_manager()

    
    class Meta:
        db_table = 'level'

    def __str__(self):
        return str(self.pk)

class Harvest(models.Model):

    #La relación de uno más mucho siempre tiene que estar los parametros. User, on_delete, related_name
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="Level",
    )

    trash_can = models.ForeignKey(
        TrashCan,
        on_delete=models.CASCADE,
        related_name="TrashCan",
    )

    date = models.DateField()

    STATUS = (
        (0, 'Por Recoger'),
        (1, 'Trabajo Hecho'),
    )

    status = models.BooleanField(
        max_length=50,
        choices=STATUS,
        default=0,
    )

    comment = models.TextField(
        blank=True,
        null=True,
    )

    def __str__(self):
        return str(self.pk)

    class Meta:
        db_table = 'harvest'
        unique_together = ('user','trash_can','date')

#

trashcan/forms.py
from django import forms
from django.forms import ModelForm

from .models import TrashCan


class TrashCanForm(ModelForm):
    
    class Meta:
        model = TrashCan
        #fields = '__all__'
        exclude = (
            'recyclers',
        )

trashcan/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import TrashCan, Level

from django.shortcuts import redirect
from django.views.generic import View
from .forms import TrashCanForm
from .serializers import TrashCanSerializer, LevelSerializer
from rest_framework import routers, serializers, viewsets


def my_view(request):
    template_name = 'trashcan/lista.html'
    context = {
        'cans': TrashCan.objects.get_lat_lng(),
    }
    return render (request,template_name,context)

class CreateView(View):
    template_name = "trashcan/crear.html"

    form = TrashCanForm

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('home_app:home')
        context = {
            'errors': kwargs.get('errors'),
            'form': self.form,
        }
        return render(request, self.template_name, context)

    def post(self, request):

        form = self.form(request.POST)
        
        if form.is_valid():
            data = dict(request.POST)
            data.pop('csrfmiddlewaretoken')

            data = {k: v[0] for k, v in data.items()}
            TrashCan.objects.create(
                **data
            )
            return redirect('trashcan_app:can-list')
        return self.get(request, errors=form.errors)


class ListView(View):

    template_name = "trashcan/detalle.html"

    def get(self, request, *args, **kwargs):

        if not request.user.is_authenticated:
            return redirect('home_app:home')

        context = {
            'errors': kwargs.get('errors'),
            'can': TrashCan.objects.filter(pk=kwargs.get('pk')).first(),
            'levels': Level.objects.get_levels(kwargs.get('pk')),
        }        
        return render(request, self.template_name, context)


class TrashCanViewSet(viewsets.ModelViewSet):
    queryset = TrashCan.objects.all()
    serializer_class = TrashCanSerializer


class LevelViewSet(viewsets.ModelViewSet):
    queryset = Level.objects.all()
    serializer_class = LevelSerializer



# Create your views here.
def my_view_crear(request):
    return HttpResponse('<h1>Yo creo</h1>')

def my_view_detail(request, id):
    return HttpResponse('<h1>Yo soy el detalle {}</h1>'.format(id))

templates/trashcan/crear.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Inicio</title>
    
</head>
<body>
    <style>        
        .tachos, .sesion{
            display: flex;
            align-items: center;
            justify-content: center
        }

        .spacing{
            margin-right: 10px;
        }
        a:hover{
            text-decoration: none;
        }
    </style>
    <div class="container">
        <div class="col-md-12 ">
            <div class="mt-5 mb-5">
                <a href="{% url 'trashcan_app:can-list' %}">
                    <button type="button" class="btn btn-outline-secondary">Volver</button>
                </a>
            </div>
            <h1 class="text-center mt-5 mb-5">Crear Tacho</h1>
            <p class="text-center">Con esta aplicación puedes saber como esta los tachos inteligentes</p>
        </div>
        
        {% if errors %}
            {{errors}}
        {% endif %}
            
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <form action="{% url 'trashcan_app:can-create' %}" method="POST">
                        {% csrf_token %} 
                        {{form.as_p}}

<!--                         <div class="form-group">
                            <label for="exampleInputEmail1">Usuario</label>
                            <input type="text" class="form-control" name="username" placeholder="Ingresa Usuario">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Password</label>
                            <input type="password" class="form-control" name="password" placeholder="Ingresa Contraseña">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Nombres</label>
                            <input type="text" class="form-control" name="first_name" placeholder="Ingresa tu nombre">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Apellidos</label>
                            <input type="text" class="form-control" name="last_name" placeholder="Ingresa tu apellido">
                        </div> -->
                        <button type="submit" class="btn btn-primary">Registrate</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/trashcan/detalle.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Listado de los Tachos</title>
    <!--<link rel="stylesheet" href="{% static 'css/home.css' %}">-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <style>        
        .tachos, .sesion{
            display: flex;
            align-items: center;
            justify-content: center
        }

        .spacing{
            margin-right: 10px;
        }
    </style>
    <div class="container">
        <div class="mt-5 mb-5">
            <a href="{% url 'trashcan_app:can-list' %}">
                <button type="button" class="btn btn-outline-secondary">Volver</button>
            </a>
        </div>
        <div class="col-md-5">
            <h2>Detalle del tacho: {{can.pk}}</h2>
            <div class="card mt-5 shadow-lg" >
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Profundidad: {{can.depth}}</li>
                    <li class="list-group-item">Código de barra: {{can.barcode}}</li>
                    <li class="list-group-item">Latitud: {{can.lat}}</li>
                    <li class="list-group-item">Longitud: {{can.lng}}</li>
                    <li class="list-group-item">Dirección: {{can.address}}</li>
                </ul>
            </div>
        </div>

        <div class="col-md-12">

            <h3 class="mt-5 mb-3">Nivel</h3>
            
            
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Tiempo</th>
                            <th scope="col">Distancia</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for level in  levels %}
                        <tr>
                            <td>{{level.id}}</td>
                            <td>{{level.time}}</td>
                            <td>{{level.distance}}</td>
                        </tr>
                        {% endfor %}                
                    </tbody>
                </table>
        </div>

            

    </div>
</body>
</html>

templates/trashcan/lista.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Listado de los Tachos</title>
    <!--<link rel="stylesheet" href="{% static 'css/home.css' %}">-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <style>        
        .tachos, .sesion{
            display: flex;
            align-items: center;
            justify-content: center
        }

        .spacing{
            margin-right: 10px;
        }
    </style>
    <div class="container">
        <div class="mt-5 mb-5">
            <a href="{% url 'trashcan_app:can-create' %}" >
                <button type="button" class="btn btn-primary">Crear Tacho</button>
            </a> 
        </div>
        <h1>Tachos</h1>
        
        <table class="table table-dark mt-4">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Profundidad</th>
                    <th scope="col">Codigo de barra</th>
                    <th scope="col">Latitud</th>
                    <th scope="col">Longitud</th>
                    <th scope="col">Dirección</th>
                </tr>
            </thead>
            <tbody>
                    {% for can in cans %}
                    <tr>
                        <th scope="row">
                            <a href={%url 'trashcan_app:can-detail' can.pk%}>
                                <button type="button" class="btn btn-outline-light">{{can.pk}}</button>
                            </a>
                        </th>
                        <td>{{can.depth}}</td>
                        <td>{{can.barcode}}</td>
                        <td>{{can.lat}}</td>
                        <td>{{can.lng}}</td>
                        <td>{{can.address}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        <div class="mt-5 mb-5">
            <a href="{% url 'home_app:home' %}">
                <button type="button" class="btn btn-outline-secondary">Volver</button>
            </a>
        </div>
    </div>
    <div id="map" style="width:100%; height:400px"></div>
    <script>

            // The following example creates complex markers to indicate beaches near
            // Sydney, NSW, Australia. Note that the anchor is set to (0,32) to correspond
            // to the base of the flagpole.
      
            function initMap() {
              var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 15,
                center: {lat: -12.070242, lng: -77.042152}
              });
      
              setMarkers(map);
            }
      
            // Data for the markers consisting of a name, a LatLng and a zIndex for the
            // order in which these markers should display on top of each other.



            var beaches = [
                {% for can in cans %}
                    ['{{can.address}}', {{can.lat}}, {{can.lng}},  {{can.pk}}],
                {% endfor %}
            ];


            /*var beaches = [
              ['Bondi Beach', -33.890542, 151.274856, 4],
              ['Coogee Beach', -33.923036, 151.259052, 5],
              ['Cronulla Beach', -34.028249, 151.157507, 3],
              ['Manly Beach', -33.80010128657071, 151.28747820854187, 2],
              ['Maroubra Beach', -33.950198, 151.259302, 1]
            ];*/
      
            function setMarkers(map) {
              // Adds markers to the map.
      
              // Marker sizes are expressed as a Size of X,Y where the origin of the image
              // (0,0) is located in the top left of the image.
      
              // Origins, anchor positions and coordinates of the marker increase in the X
              // direction to the right and in the Y direction down.
              var image = {
                url: 'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png',
                // This marker is 20 pixels wide by 32 pixels high.
                size: new google.maps.Size(20, 32),
                // The origin for this image is (0, 0).
                origin: new google.maps.Point(0, 0),
                // The anchor for this image is the base of the flagpole at (0, 32).
                anchor: new google.maps.Point(0, 32)
              };
              // Shapes define the clickable region of the icon. The type defines an HTML
              // <area> element 'poly' which traces out a polygon as a series of X,Y points.
              // The final coordinate closes the poly by connecting to the first coordinate.
              var shape = {
                coords: [1, 1, 1, 20, 18, 20, 18, 1],
                type: 'poly'
              };
              for (var i = 0; i < beaches.length; i++) {
                var beach = beaches[i];
                var marker = new google.maps.Marker({
                  position: {lat: beach[1], lng: beach[2]},
                  map: map,
                  icon: image,
                  shape: shape,
                  title: beach[0],
                  zIndex: beach[3]
                });
              }
            }
          </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAgPdjgx9UcWpDjn5-iye-sI2HHfgnni_A&callback=initMap"
    async defer></script>
 

</body>
</html>